### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by schowdhuryUMD** [RishieVyas/smarter-university-system#9]
Child of #3 Software Testing. Write unit tests that break the quizzes module.

**Comment by RishieVyas** [comment]
Created unit test case which breaks the code at add_quiz function

**Comment by RishieVyas** [comment]
Generated a unit test case, which breaks the code at the add_question function

**Comment by Rbhatt24** [comment]
Unit Test Cases were added identifying break point of the functrions.
